name: Release

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  create-release:
    name: Create a Release

    needs: [test]

    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'npm'

      - run: npm ci

      - run: npm run compile

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
