name: Release

on:
  # exec on merge
  push:
    branches: [main]

jobs:
  create-release:
    name: Create a Release

    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.set-version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "Royce Nobles"
          git config user.email "ranobles@gmail.com"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install
        run: npx ci

      - name: Compile
        run: npm run compile

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # - name: Set version
      #   id: set-version
      #   run: |
      #     echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
